package com.example.svc;

import android.Manifest;
import android.app.AlertDialog;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.os.Build;
import android.os.Bundle;
import android.view.View;
import android.widget.EditText;

import androidx.annotation.RequiresApi;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.app.ActivityCompat;
import androidx.core.content.ContextCompat;

import com.google.android.material.textfield.TextInputEditText;

import Utils.Constants;
import models.SVCDB;
import models.UserDAO;
import models.UserDTO;

@RequiresApi(api = Build.VERSION_CODES.KITKAT)
public class MainActivity extends AppCompatActivity {
    /**
     * Instance variables:
     * db - an instance of the SQLite Helper class.
     */
    private SVCDB db;

    /**
     * {@inheritDoc}
     * Initializes the db instance, gets permissions from the user.
     * @param savedInstanceState {@inheritDoc}
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        db = new SVCDB(this);
        //get permissions from the user at startup..
        if (ContextCompat.checkSelfPermission(this, Manifest.permission.WRITE_CONTACTS) != PackageManager.PERMISSION_GRANTED) {
            ActivityCompat.requestPermissions(this, new String[]{Manifest.permission.WRITE_CONTACTS}, 0);
        }
        if (ContextCompat.checkSelfPermission(this, Manifest.permission.RECORD_AUDIO) != PackageManager.PERMISSION_GRANTED) {
            ActivityCompat.requestPermissions(this, new String[]{Manifest.permission.RECORD_AUDIO}, 0);
        }

    }

    /**
     * the onClick for the <i>Login</i> button.
     * gets the input from the textFields, validates non-emptiness.
     * Attempts to login, if successful opens the Home Activity (passing the user object via the intent). If not, displays an appropriate error.
     * @param v <code>Auto-generated by Android</code>
     */
    public void login(View v){
        String email = ((TextInputEditText) findViewById(R.id.emailTF)).getText().toString();
        String password = ((EditText) findViewById(R.id.passwordTF)).getText().toString();
        //input validation
        //-----------------------------------------------
        if(email.isEmpty() || password.isEmpty()){
            new AlertDialog.Builder(this)
                    .setTitle("Missing Fields")
                    .setMessage("Email and/or password is missing")
                    .setNeutralButton("Close", null)
                    .setIcon(android.R.drawable.ic_dialog_alert)
                    .show();
            return;
        }
        //-----------------------------------------------
        UserDTO user;
        if((user = UserDAO.login(new UserDTO.Builder().
                                            setEmail(email).
                                            setPassword(password,true).
                                            build(),db)) != null){
            Intent intent = new Intent(this,Home.class);
            intent.putExtra(Constants.USER,user.toString());
            startActivity(intent);
        }else{
            new AlertDialog.Builder(this)
                    .setTitle("Wrong Credentials, Sorry :(")
                    .setMessage("Email and/or password is invalid")
                    .setNeutralButton("Close", null)
                    .setIcon(android.R.drawable.ic_dialog_alert)
                    .show();
        }
    }
    /**
     * the onClick for the <i>Register</i> link.
     * takes the user to the registration page
     * @param v <code>Auto-generated by Android</code>
     */
    public void register(View v){
        Intent intent = new Intent(this,SignUp.class);
        startActivity(intent);
    }
}