package com.example.svc;

import android.app.AlertDialog;
import android.content.Intent;
import android.os.Build;
import android.os.Bundle;
import android.view.View;
import android.widget.EditText;

import androidx.annotation.RequiresApi;
import androidx.appcompat.app.AppCompatActivity;

import Utils.Constants;
import models.SVCDB;
import models.UserDAO;
import models.UserDTO;
import security.InputValidators;

@RequiresApi(api = Build.VERSION_CODES.KITKAT)
public class ResetPassword extends AppCompatActivity {
    /**
     * Instance variables:
     * db - an instance of the SQLite Helper class.
     * user - The currently logged in user.
     */
    private UserDTO user;
    private SVCDB db;

    /**
     * {@inheritDoc}
     * Initializes the db instance, gets the currently logged in user from the intent <i>Extra</i> dictionary.
     * @param savedInstanceState {@inheritDoc}
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_reset_password);
        db = new SVCDB(this);
        Intent intent = getIntent();

        user = UserDTO.stringToUser(intent.getStringExtra(Constants.USER));

    }

    /**
     * the onClick for the <i>Change Password</i> button.
     * gets the input from the textFields, validates it. Then changes the password in the DB.
     * @param v <code>Auto-generated by Android</code>
     */
    public void editPassword(View v){
        String password1 = ((EditText) findViewById(R.id.passwordeditTR)).getText().toString();
        String password2 = ((EditText) findViewById(R.id.passwordconfirmTR)).getText().toString();

        //validate input
        //---------------------------------------------------------------------

        if(password1.isEmpty() || password2.isEmpty()){
            new AlertDialog.Builder(this)
                    .setTitle("Invalid input")
                    .setMessage("One or more of the fields is missing")
                    .setNeutralButton("Close", null)
                    .setIcon(android.R.drawable.ic_dialog_alert)
                    .show();
            return;
        }

        if(!password1.equals(password2)) {
            new AlertDialog.Builder(this)
                    .setTitle("Passwords do not match")
                    .setMessage("Please recheck the passwords and make sure they match")
                    .setNeutralButton("Close", null)
                    .setIcon(android.R.drawable.ic_dialog_alert)
                    .show();
            return;
        }
        if(!InputValidators.validate(InputValidators.PASSWORD,password1)){
            new AlertDialog.Builder(this)
                    .setTitle("Invalid input")
                    .setMessage("Password must be at least 8 characters long and contain at least 1 digit, 1 small case letter, and 1 upper case letter.")
                    .setNeutralButton("Close", null)
                    .setIcon(android.R.drawable.ic_dialog_alert)
                    .show();
            return;
        }
        //----------------------------------------------------------------------
        //update the password in the DB and move to the Home screen
        if(UserDAO.resetPassword(new UserDTO.Builder().
                setEmail(user.getEmail()).
                setFull_name(user.getFull_name()).
                setPassword(password1,true)
                .build(),db)) {
            Intent intent = new Intent(this, Home.class);
            intent.putExtra(Constants.USER,user.toString());
            startActivity(intent);
        }
        //TODO: display alert in case of error.
        else{
            new AlertDialog.Builder(this)
                    .setTitle("This password wasn't updated.")
                    .setMessage("Please try again!")
                    .setNeutralButton("Close", null)
                    .setIcon(android.R.drawable.ic_dialog_alert)
                    .show();
        }
    }
}