package com.example.svc;

import android.app.AlertDialog;
import android.content.Intent;
import android.os.Build;
import android.os.Bundle;
import android.view.View;

import androidx.annotation.RequiresApi;
import androidx.appcompat.app.AppCompatActivity;

import models.SVCDB;
import models.User;

@RequiresApi(api = Build.VERSION_CODES.O)
public class SignUp extends AppCompatActivity {
    /**
     * Instance variables:
     * db - an instance of the SQLite Helper class.
     */
    private SVCDB db;
    String id = "054";
    String encounter_time = "0";//change in the process.

    /**
     * {@inheritDoc}
     * Initializes the db instance.
     * @param savedInstanceState {@inheritDoc}
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_sign_up);
        db = new SVCDB(this);
    }

    /**
     * the onClick of the <i>Sign up</i> button.
     * gets the input from the textFields, validates it. Then registers the user in the database - displays an alert in case of error.
     * @param v <code>Auto-generated by Android</code>
     */
    public void signUp(View v){
        String id = "054"; // TAL - need to get from phone

        //Sign up to the cloud???


    }
}