package com.example.svc;

import android.app.AlertDialog;
import android.content.Intent;
import android.os.Build;
import android.os.Bundle;
import android.view.View;
import android.widget.EditText;

import androidx.annotation.RequiresApi;
import androidx.appcompat.app.AppCompatActivity;

import com.google.android.material.textfield.TextInputEditText;

import models.SVCDB;
import models.UserDAO;
import models.UserDTO;
import security.InputValidators;

@RequiresApi(api = Build.VERSION_CODES.O)
public class SignUp extends AppCompatActivity {
    /**
     * Instance variables:
     * db - an instance of the SQLite Helper class.
     */
    private SVCDB db;
    String id = "054";
    String encounter_time = "0";//change in the process.

    /**
     * {@inheritDoc}
     * Initializes the db instance.
     * @param savedInstanceState {@inheritDoc}
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_sign_up);
        db = new SVCDB(this);
    }

    /**
     * the onClick of the <i>Sign up</i> button.
     * gets the input from the textFields, validates it. Then registers the user in the database - displays an alert in case of error.
     * @param v <code>Auto-generated by Android</code>
     */
    public void signUp(View v){
        String id = "054"; // TAL - need to get from phone

        //validate input
        //---------------------------------------------------------------------

        if(id.isEmpty()){
            new AlertDialog.Builder(this)
                    .setTitle("Invalid input")
                    .setMessage("One or more of the fields is missing")
                    .setNeutralButton("Close", null)
                    .setIcon(android.R.drawable.ic_dialog_alert)
                    .show();
            return;
        }

        //----------------------------------------------------------------------
        //save the newly created use in the DB

        if(UserDAO.signUp(new UserDTO.Builder().
            setId(id).build(),db)){ //TAL - to fix
            Intent intent = new Intent(this,MainActivity.class);
            startActivity(intent);
        }else{
            new AlertDialog.Builder(this)
                    .setTitle("You already have an account!")
                    .setMessage("Please go to the login page and login!")
                    .setNeutralButton("Close", null)
                    .setIcon(android.R.drawable.ic_dialog_alert)
                    .show();
        }
    }
}