package com.example.svc;

import android.app.AlertDialog;
import android.content.Intent;
import android.os.Build;
import android.os.Bundle;
import android.util.Log;
import android.view.View;

import androidx.annotation.RequiresApi;
import androidx.appcompat.app.AppCompatActivity;

import SenderPackage.Sender;
import Utils.Constants;
import Utils.Smaz;
import models.Encounter;
import models.SVCDB;
import models.User;

@RequiresApi(api = Build.VERSION_CODES.KITKAT)/*change to oreo version of OS*/
public class ViewVisitCard extends AppCompatActivity {
    /**
     * Instance variables:
     * db - an instance of the SQLite Helper class.
     * user - The currently logged in user.
     * vc - the visit card to view.
     */
    private SVCDB db;
    private Encounter vc;
    private User user;

    /**
     * {@inheritDoc}
     * Initializes the db instance, gets the currently logged in user, and the visit card from the intent <i>Extra</i> dictionary.
     * Initializes the textViews with the values of the received visit card.
     * @param savedInstanceState {@inheritDoc}
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_view_visit_card);
        db = new SVCDB(this);
        //get the data from the intent dictionary
        Intent intent = getIntent();
        user = new User(intent.getStringExtra(Constants.USER));

    }


    /**
     * the onClick of the <i>Delete</i> button.
     * Deletes the visit card from the DB and from the phone book.
     * @param v <code>Auto-generated by Android</code>
     */
    public void Delete(View v){
        //TODO: delete from phone book (if possible)
        if(Encounter.deleteVC( vc.getId(),db)){
            Intent intent = new Intent(this,Home.class);
            //putExtra
            intent.putExtra(Constants.USER,user.toString());
            startActivity(intent);
        }else{
            //TODO: check if the visit card exists by comparing all the values not by ID
            new AlertDialog.Builder(this)
                    .setTitle("This visit card wasn't deleted.")
                    .setMessage("Please try again!")
                    .setNeutralButton("Close", null)
                    .setIcon(android.R.drawable.ic_dialog_alert)
                    .show();

        }
    }

    /**
     * the onClick of the <i>Send</i> button.
     * sends the visit card over sound. convert it to string, compress it and send it.
     * @param frame Frame to send.
     */
    public void Send(String frame){
        Log.d("debug", "Send on ViewVisitCard");
        String binaryRep = Utils.utils.strToBinary(frame);

        if (!binaryRep.isEmpty() && !binaryRep.equals("")) {
            Sender cSender = new Sender();
            cSender.setMsg2Send(binaryRep);
            //TODO Rani: add Alert with progress bar
            cSender.sendMsg();
        }
    }
}