package com.example.svc;

import android.content.Intent;
import android.os.Build;
import android.os.Bundle;
import android.view.View;
import android.widget.EditText;

import androidx.annotation.RequiresApi;
import androidx.appcompat.app.AppCompatActivity;

import Utils.Constants;
import models.SVCDB;
import models.UserDTO;
@RequiresApi(api = Build.VERSION_CODES.KITKAT)
public class ViewProfile extends AppCompatActivity {
    /**
     * Instance variables:
     * db - an instance of the SQLite Helper class.
     * user - The currently logged in user.
     */
    private SVCDB db;
    private UserDTO user;

    /**
     * {@inheritDoc}
     * Initializes the db instance, gets the currently logged in user from the intent <i>Extra</i> dictionary.
     * sets the TextFields value to that stored in the current user.
     * @param savedInstanceState {@inheritDoc}
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_view_profile);
        db = new SVCDB(this);
        Intent intent = getIntent();
        //get the user from the intent dictionary
        user = UserDTO.stringToUser(intent.getStringExtra(Constants.USER));

        //set the text of the email and the full_name textFields
        EditText full_name = (EditText) findViewById(R.id.fullNameinfoTR);
        full_name.setText(user.getFull_name());

        EditText email = (EditText) findViewById(R.id.emailinfoTR);
        email.setText(user.getEmail());
    }

    /***
     * the onClick of the <i>Reset Password</i> button.
     * takes the user to the Reset Password screen.
     * @param v <code>Auto-generated by Android</code>
     */
    public void editInfo(View v){
        Intent intent = new Intent(this,ResetPassword.class);
        intent.putExtra(Constants.USER,user.toString());
        startActivity(intent);
    }
}