package com.example.svc;

import android.app.AlertDialog;
import android.content.Intent;
import android.os.Build;
import android.os.Bundle;
import android.view.View;
import android.widget.TextView;

import androidx.annotation.RequiresApi;
import androidx.appcompat.app.AppCompatActivity;

import SenderPackage.Sender;
import Utils.Constants;
import Utils.Smaz;
import models.SVCDB;
import models.UserDTO;
import models.VisitCardDAO;
import models.VisitCardDTO;

@RequiresApi(api = Build.VERSION_CODES.KITKAT)
public class ViewVisitCard extends AppCompatActivity {
    /**
     * Instance variables:
     * db - an instance of the SQLite Helper class.
     * user - The currently logged in user.
     * vc - the visit card to view.
     */
    private SVCDB db;
    private VisitCardDTO vc;
    private UserDTO user;

    /**
     * {@inheritDoc}
     * Initializes the db instance, gets the currently logged in user, and the visit card from the intent <i>Extra</i> dictionary.
     * Initializes the textViews with the values of the received visit card.
     * @param savedInstanceState {@inheritDoc}
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_view_visit_card);
        db = new SVCDB(this);
        //get the data from the intent dictionary
        Intent intent = getIntent();
        vc = VisitCardDTO.stringToVisitCard(intent.getStringExtra(Constants.VC_DATA));
        user = UserDTO.stringToUser(intent.getStringExtra(Constants.USER));

        //set the text of the textViews from the received visit card:

        //set email textView
        TextView email = (TextView) findViewById(R.id.emailTextView);
        email.setText("Email: " + vc.getEmail());
        //set full name textView
        TextView full_name = (TextView) findViewById(R.id.full_nameTextView);
        full_name.setText("Full Name: " + vc.getFullName());
        //set position title textView
        TextView position_title = (TextView) findViewById(R.id.positionTextView);
        position_title.setText("Position: " + vc.getPosition_title());
        //set company textView
        TextView company = (TextView) findViewById(R.id.companyTextView);
        company.setText("Company: " + vc.getCompany());
        //set address textView
        TextView address = (TextView) findViewById(R.id.addressTextView);
        address.setText("Address: " + vc.getAddress());
        //set telephone textView
        TextView telephone = (TextView) findViewById(R.id.telephoneTextView);
        telephone.setText("Telephone: " + vc.getTelephone());
        //set fax textView
        TextView fax = (TextView) findViewById(R.id.faxTextView);
        fax.setText("Fax: " + vc.getFax());
        //set mobile textView
        TextView mobile = (TextView) findViewById(R.id.mobileTextView);
        mobile.setText("Mobile: " + vc.getMobile());
        //set website textView
        TextView website = (TextView) findViewById(R.id.websiteTextView);
        website.setText("Website: " + vc.getWebsite());
    }


    /**
     * the onClick of the <i>Delete</i> button.
     * Deletes the visit card from the DB and from the phone book.
     * @param v <code>Auto-generated by Android</code>
     */
    public void Delete(View v){
        //TODO: delete from phone book (if possible)
        if(VisitCardDAO.deleteVC( vc.getId(),db)){
            Intent intent = new Intent(this,Home.class);
            //putExtra
            intent.putExtra(Constants.USER,user.toString());
            startActivity(intent);
        }else{
            //TODO: check if the visit card exists by comparing all the values not by ID
            new AlertDialog.Builder(this)
                    .setTitle("This visit card wasn't deleted.")
                    .setMessage("Please try again!")
                    .setNeutralButton("Close", null)
                    .setIcon(android.R.drawable.ic_dialog_alert)
                    .show();

        }
    }

    /**
     * the onClick of the <i>Send</i> button.
     * sends the visit card over sound. convert it to string, compress it and send it.
     * @param v <code>Auto-generated by Android</code>
     */
    public void Send(View v){
        //if algorithm is Smaz
        Smaz smaz = new Smaz();
        byte[] compressedVC = smaz.compress(vc.prepareForCompression());
        String binaryRep = Utils.utils.byteArrayToBinary(compressedVC);
        //if algorithm is LZString
//        String compressedVC = Utils.LZString.compress(vc.toString());
//        String binaryRep = Utils.utils.strToBinary(compressedVC);

        if (!binaryRep.isEmpty() && !binaryRep.equals(" ")) {
            Sender cSender = new Sender();
            cSender.setMsg2Send(binaryRep);
            Integer[] SettingsArr = Utils.SoundSettings.getSettings();
            //TODO Rani: add Alert with progress bar
            cSender.sendMsg(SettingsArr);
        }
    }

    /**
     * the onClick of the <i>Edit</i> button.
     * opens the EditVC screen.
     * @param v <code>Auto-generated by Android</code>
     */
    public void Edit(View v){
        Intent intent = new Intent(this,EditVC.class);
        //pass the current user and the vc to edit.
        intent.putExtra(Constants.VC_DATA,vc.toString());
        intent.putExtra(Constants.USER,user.toString());
        startActivity(intent);
    }
}